server.port=${PORT:8080}
spring.application.name=lms-backend

# ===============================
# Database (Non-Sensitive Values)
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d7hrsrfavr4c73f9fefg-a.oregon-postgres.render.com:5432/lmsdb_hnig
spring.datasource.username=lmsdb_hnig_user
spring.datasource.password=C8B2QuozLND83qQCJlrsXX6hNeEWhpIx
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# ===============================
# Load Sensitive Properties
# ===============================
spring.profiles.active=secret

# ===============================
# JWT Configuration
# ===============================
app.jwt.secret=ReplaceThisWithAStrongRandomSecretOfAtLeast32Chars!
app.jwt.expiration-ms=86400000



# ===============================
# Email Configuration (Gmail SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=no.reply.lms0@gmail.com
spring.mail.password=cankyqspyejinkxh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OTP config (optional)
app.otp.expire-minutes=10
app.otp.code-length=6



spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# where uploaded medical certificates go (relative to app working dir)
file.upload-dir=uploads/medical

